# -*- coding: utf-8 -*-
"""Adrian Hedrin Montilalu S.Kom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8GJUvJkUloEseFunFWqO82JuXHeaIab
"""

### 1. Mount Google Drive ###

from google.colab import drive

drive.mount('/content/gdrive')

### 2. Define root directory ###

ROOT_DIR = '/content/gdrive/My Drive/TA'

### 3. Install Ultralytics ###

!pip install ultralytics

# Mengunduh dataset dari Roboflow
# !pip install roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Aa6c3Hso23wLZBxLarVI")
project = rf.workspace("testing-hoz73").project("sedimen-stone-3.0")
version = project.version(3)
dataset = version.download("yolov8")

# Mengecek isi folder dataset
import os
os.listdir(dataset.location)

### 4. Train model ###

import os

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")

# Use the model
results = model.train(data=os.path.join(dataset.location, "data.yaml"), epochs=35, batch=32, optimizer="RMSProp")  # train the model

### 5. Copy results ###
from google.colab import drive
drive.mount('/content/gdrive')

!scp -r /content/runs '/content/gdrive/My Drive/TA/runs/detect/RMSProp35'